info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

hystrix:
  command:
    stores:
      circuitBreaker:
        requestVolumeThreshold: 10
        sleepWindowInMilliseconds: 10000
      execution:
        timeout:
          enable: false
        isolation:
          thread:
            timeoutInMilliseconds: 20000
    customers:
      circuitBreaker:
        requestVolumeThreshold: 10
        sleepWindowInMilliseconds: 10000
      execution:
        timeout:
          enable: false
        isolation:
          thread:
            timeoutInMilliseconds: 20000
    zuulserver:
      circuitBreaker:
        requestVolumeThreshold: 10
        sleepWindowInMilliseconds: 10000
      execution:
        timeout:
          enable: false
        isolation:
          thread:
            timeoutInMilliseconds: 20000

stores:
  ribbon:
    listOfServers: http://localhost:9995/, http://localhost:9997/
customers:
  ribbon:
    listOfServers: http://localhost:9999/
zuulserver:
  ribbon:
    listOfServers: http://localhost:8765/

zuul:
  routes:
    stores:
      path: /stores/**
      serviceId: stores
    customers:
      path: /customers/**
      serviceId: customers
    zuulserver:
      path: /self/**
      serviceId: zuulserver

ribbon:
  eureka:
    enabled: false

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
