info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    stores:
      path: /stores/**
      serviceId: stores
      url: http://localhost:9997
    customers:
      path: /customers/**
      serviceId: customers
      url: http://localhost:9999
    zuulserver:
      path: /self/**
      serviceId: zuulserver
      url: http://localhost:8765/

ribbon:
  eureka:
    enabled: false

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
